### ISSUE TITLE
docker image frekele/apache-ant was renamed to frekele/ant

### ISSUE THREAD

**Issue by christian-schwarzbauer** [dynatrace-innovationlab/easyTravel-Builder#1]
`build-in-docker.sh` references docker hub image `frekele/apache-ant` which does not exist any longer.
`frekele/ant` has to be used instead.

**Comment by metmajer** [comment]
Thanks @christian-schwarzbauer! Resolved via https://github.com/dynatrace-innovationlab/easyTravel-Builder/commit/13d0f7f9aeac7679197add9c199ad0c67f02c75a.
